name: launchdarkly_flutter
description: This is a LaunchDarkly SDK for Flutter, for anyone willing to use LaunchDarkly in a Flutter app.
version: 0.6.2
homepage: https://github.com/andre-paraense/launchdarkly_flutter
issue_tracker: https://github.com/andre-paraense/launchdarkly_flutter/issues

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.oakam.launchdarkly_flutter
        pluginClass: LaunchdarklyFlutterPlugin
      ios:
        pluginClass: LaunchdarklyFlutterPlugin